[project]
name = "plot-statistical-distributions"
version = "0.1.0"
description = "Add a short description here"
authors = ["Narinder Singh <7772391+nsingh-phd@users.noreply.github.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]
jupyterlab = "jupyter lab"

[dependencies]
scipy = ">=1.13.0,<1.14"
numpy = ">=1.26.4,<1.27"
python = "3.11.*"
matplotlib = ">=3.8.4,<3.9"
jupyterlab = ">=4.2.0,<4.3"
